$(function(){$(".row").fadeIn(500,"linear");$("#navigationbar").affix({})});(function(b){b(function(){b.support.transition=function(){var g=function(){var i=document.createElement("bootstrap"),a={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},c;for(c in a)if(i.style[c]!==undefined)return a[c]}();return g&&{end:g}}()})})(window.jQuery);
(function(b){var g=function(a){b(a).on("click",'[data-dismiss="alert"]',this.close)};g.prototype.close=function(a){function c(){f.trigger("closed").remove()}var d=b(this),e=d.attr("data-target"),f;if(!e)e=(e=d.attr("href"))&&e.replace(/.*(?=#[^\s]*$)/,"");f=b(e);a&&a.preventDefault();f.length||(f=d.hasClass("alert")?d:d.parent());f.trigger(a=b.Event("close"));if(!a.isDefaultPrevented()){f.removeClass("in");b.support.transition&&f.hasClass("fade")?f.on(b.support.transition.end,c):c()}};var i=b.fn.alert;
b.fn.alert=function(a){return this.each(function(){var c=b(this),d=c.data("alert");d||c.data("alert",d=new g(this));typeof a=="string"&&d[a].call(c)})};b.fn.alert.Constructor=g;b.fn.alert.noConflict=function(){b.fn.alert=i;return this};b(document).on("click.alert.data-api",'[data-dismiss="alert"]',g.prototype.close)})(window.jQuery);
(function(b){var g=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.button.defaults,c)};g.prototype.setState=function(a){var c=this.$element,d=c.data(),e=c.is("input")?"val":"html";a+="Text";d.resetText||c.data("resetText",c[e]());c[e](d[a]||this.options[a]);setTimeout(function(){a=="loadingText"?c.addClass("disabled").attr("disabled","disabled"):c.removeClass("disabled").removeAttr("disabled")},0)};g.prototype.toggle=function(){var a=this.$element.closest('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};var i=b.fn.button;b.fn.button=function(a){return this.each(function(){var c=b(this),d=c.data("button"),e=typeof a=="object"&&a;d||c.data("button",d=new g(this,e));if(a=="toggle")d.toggle();else a&&d.setState(a)})};b.fn.button.defaults={loadingText:"loading..."};b.fn.button.Constructor=g;b.fn.button.noConflict=function(){b.fn.button=i;return this};b(document).on("click.button.data-api","[data-toggle^=button]",function(a){a=
b(a.target);a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle")})})(window.jQuery);
(function(b){var g=function(a,c){this.$element=b(a);this.$indicators=this.$element.find(".carousel-indicators");this.options=c;this.options.pause=="hover"&&this.$element.on("mouseenter",b.proxy(this.pause,this)).on("mouseleave",b.proxy(this.cycle,this))};g.prototype={cycle:function(a){if(!a)this.paused=false;this.interval&&clearInterval(this.interval);this.options.interval&&!this.paused&&(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this},getActiveIndex:function(){this.$active=
this.$element.find(".item.active");this.$items=this.$active.parent().children();return this.$items.index(this.$active)},to:function(a){var c=this.getActiveIndex(),d=this;if(!(a>this.$items.length-1||a<0)){if(this.sliding)return this.$element.one("slid",function(){d.to(a)});if(c==a)return this.pause().cycle();return this.slide(a>c?"next":"prev",b(this.$items[a]))}},pause:function(a){if(!a)this.paused=true;if(this.$element.find(".next, .prev").length&&b.support.transition.end){this.$element.trigger(b.support.transition.end);
this.cycle()}clearInterval(this.interval);this.interval=null;return this},next:function(){if(!this.sliding)return this.slide("next")},prev:function(){if(!this.sliding)return this.slide("prev")},slide:function(a,c){var d=this.$element.find(".item.active"),e=c||d[a]();c=this.interval;var f=a=="next"?"left":"right",h=a=="next"?"first":"last",j=this;this.sliding=true;c&&this.pause();e=e.length?e:this.$element.find(".item")[h]();h=b.Event("slide",{relatedTarget:e[0],direction:f});if(!e.hasClass("active")){if(this.$indicators.length){this.$indicators.find(".active").removeClass("active");
this.$element.one("slid",function(){var k=b(j.$indicators.children()[j.getActiveIndex()]);k&&k.addClass("active")})}if(b.support.transition&&this.$element.hasClass("slide")){this.$element.trigger(h);if(h.isDefaultPrevented())return;e.addClass(a);d.addClass(f);e.addClass(f);this.$element.one(b.support.transition.end,function(){e.removeClass([a,f].join(" ")).addClass("active");d.removeClass(["active",f].join(" "));j.sliding=false;setTimeout(function(){j.$element.trigger("slid")},0)})}else{this.$element.trigger(h);
if(h.isDefaultPrevented())return;d.removeClass("active");e.addClass("active");this.sliding=false;this.$element.trigger("slid")}c&&this.cycle();return this}}};var i=b.fn.carousel;b.fn.carousel=function(a){return this.each(function(){var c=b(this),d=c.data("carousel"),e=b.extend({},b.fn.carousel.defaults,typeof a=="object"&&a),f=typeof a=="string"?a:e.slide;d||c.data("carousel",d=new g(this,e));if(typeof a=="number")d.to(a);else if(f)d[f]();else e.interval&&d.pause().cycle()})};b.fn.carousel.defaults=
{interval:5E3,pause:"hover"};b.fn.carousel.Constructor=g;b.fn.carousel.noConflict=function(){b.fn.carousel=i;return this};b(document).on("click.carousel.data-api","[data-slide], [data-slide-to]",function(a){var c=b(this),d,e=b(c.attr("data-target")||(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""));d=b.extend({},e.data(),c.data());e.carousel(d);if(c=c.attr("data-slide-to"))e.data("carousel").pause().to(c).cycle();a.preventDefault()})})(window.jQuery);
(function(b){var g=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.collapse.defaults,c);if(this.options.parent)this.$parent=b(this.options.parent);this.options.toggle&&this.toggle()};g.prototype={constructor:g,dimension:function(){return this.$element.hasClass("width")?"width":"height"},show:function(){var a,c,d,e;if(!(this.transitioning||this.$element.hasClass("in"))){a=this.dimension();c=b.camelCase(["scroll",a].join("-"));if((d=this.$parent&&this.$parent.find("> .accordion-group > .in"))&&
d.length){if((e=d.data("collapse"))&&e.transitioning)return;d.collapse("hide");e||d.data("collapse",null)}this.$element[a](0);this.transition("addClass",b.Event("show"),"shown");b.support.transition&&this.$element[a](this.$element[0][c])}},hide:function(){var a;if(!(this.transitioning||!this.$element.hasClass("in"))){a=this.dimension();this.reset(this.$element[a]());this.transition("removeClass",b.Event("hide"),"hidden");this.$element[a](0)}},reset:function(a){var c=this.dimension();this.$element.removeClass("collapse")[c](a||
"auto");this.$element[a!==null?"addClass":"removeClass"]("collapse");return this},transition:function(a,c,d){var e=this,f=function(){c.type=="show"&&e.reset();e.transitioning=0;e.$element.trigger(d)};this.$element.trigger(c);if(!c.isDefaultPrevented()){this.transitioning=1;this.$element[a]("in");b.support.transition&&this.$element.hasClass("collapse")?this.$element.one(b.support.transition.end,f):f()}},toggle:function(){this[this.$element.hasClass("in")?"hide":"show"]()}};var i=b.fn.collapse;b.fn.collapse=
function(a){return this.each(function(){var c=b(this),d=c.data("collapse"),e=b.extend({},b.fn.collapse.defaults,c.data(),typeof a=="object"&&a);d||c.data("collapse",d=new g(this,e));typeof a=="string"&&d[a]()})};b.fn.collapse.defaults={toggle:true};b.fn.collapse.Constructor=g;b.fn.collapse.noConflict=function(){b.fn.collapse=i;return this};b(document).on("click.collapse.data-api","[data-toggle=collapse]",function(a){var c=b(this),d;a=c.attr("data-target")||a.preventDefault()||(d=c.attr("href"))&&
d.replace(/.*(?=#[^\s]+$)/,"");d=b(a).data("collapse")?"toggle":c.data();c[b(a).hasClass("in")?"addClass":"removeClass"]("collapsed");b(a).collapse(d)})})(window.jQuery);
(function(b){function g(){b(a).each(function(){i(b(this)).removeClass("open")})}function i(e){var f=e.attr("data-target");if(!f)f=(f=e.attr("href"))&&/#/.test(f)&&f.replace(/.*(?=#[^\s]*$)/,"");f=f&&b(f);if(!f||!f.length)f=e.parent();return f}var a="[data-toggle=dropdown]",c=function(e){var f=b(e).on("click.dropdown.data-api",this.toggle);b("html").on("click.dropdown.data-api",function(){f.parent().removeClass("open")})};c.prototype={constructor:c,toggle:function(){var e=b(this),f,h;if(!e.is(".disabled, :disabled")){f=
i(e);h=f.hasClass("open");g();h||f.toggleClass("open");e.focus();return false}},keydown:function(e){var f,h,j;if(/(38|40|27)/.test(e.keyCode)){f=b(this);e.preventDefault();e.stopPropagation();if(!f.is(".disabled, :disabled")){h=i(f);j=h.hasClass("open");if(!j||j&&e.keyCode==27){e.which==27&&h.find(a).focus();return f.click()}f=b("[role=menu] li:not(.divider):visible a",h);if(f.length){h=f.index(f.filter(":focus"));e.keyCode==38&&h>0&&h--;e.keyCode==40&&h<f.length-1&&h++;~h||(h=0);f.eq(h).focus()}}}}};
var d=b.fn.dropdown;b.fn.dropdown=function(e){return this.each(function(){var f=b(this),h=f.data("dropdown");h||f.data("dropdown",h=new c(this));typeof e=="string"&&h[e].call(f)})};b.fn.dropdown.Constructor=c;b.fn.dropdown.noConflict=function(){b.fn.dropdown=d;return this};b(document).on("click.dropdown.data-api",g).on("click.dropdown.data-api",".dropdown form",function(e){e.stopPropagation()}).on(".dropdown-menu",function(e){e.stopPropagation()}).on("click.dropdown.data-api",a,c.prototype.toggle).on("keydown.dropdown.data-api",
a+", [role=menu]",c.prototype.keydown)})(window.jQuery);
(function(b){var g=function(a,c){this.options=c;this.$element=b(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",b.proxy(this.hide,this));this.options.remote&&this.$element.find(".modal-body").load(this.options.remote)};g.prototype={constructor:g,toggle:function(){return this[!this.isShown?"show":"hide"]()},show:function(){var a=this,c=b.Event("show");this.$element.trigger(c);if(!(this.isShown||c.isDefaultPrevented())){this.isShown=true;this.escape();this.backdrop(function(){var d=b.support.transition&&
a.$element.hasClass("fade");a.$element.parent().length||a.$element.appendTo(document.body);a.$element.show();a.$element.addClass("in").attr("aria-hidden",false);a.enforceFocus();d?a.$element.one(b.support.transition.end,function(){a.$element.focus().trigger("shown")}):a.$element.focus().trigger("shown")})}},hide:function(a){a&&a.preventDefault();a=b.Event("hide");this.$element.trigger(a);if(!(!this.isShown||a.isDefaultPrevented())){this.isShown=false;this.escape();b(document).off("focusin.modal");
this.$element.removeClass("in").attr("aria-hidden",true);b.support.transition&&this.$element.hasClass("fade")?this.hideWithTransition():this.hideModal()}},enforceFocus:function(){var a=this;b(document).on("focusin.modal",function(c){a.$element[0]!==c.target&&!a.$element.has(c.target).length&&a.$element.focus()})},escape:function(){var a=this;if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.modal",function(c){c.which==27&&a.hide()});else this.isShown||this.$element.off("keyup.dismiss.modal")},
hideWithTransition:function(){var a=this,c=setTimeout(function(){a.$element.off(b.support.transition.end);a.hideModal()},500);this.$element.one(b.support.transition.end,function(){clearTimeout(c);a.hideModal()})},hideModal:function(){var a=this;this.$element.hide();this.backdrop(function(){a.removeBackdrop();a.$element.trigger("hidden")})},removeBackdrop:function(){this.$backdrop.remove();this.$backdrop=null},backdrop:function(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var d=
b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.$backdrop.click(this.options.backdrop=="static"?b.proxy(this.$element[0].focus,this.$element[0]):b.proxy(this.hide,this));this.$backdrop.addClass("in");if(a)d?this.$backdrop.one(b.support.transition.end,a):a()}else if(!this.isShown&&this.$backdrop){this.$backdrop.removeClass("in");b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,a):a()}else a&&
a()}};var i=b.fn.modal;b.fn.modal=function(a){return this.each(function(){var c=b(this),d=c.data("modal"),e=b.extend({},b.fn.modal.defaults,c.data(),typeof a=="object"&&a);d||c.data("modal",d=new g(this,e));if(typeof a=="string")d[a]();else e.show&&d.show()})};b.fn.modal.defaults={backdrop:true,keyboard:true,show:true};b.fn.modal.Constructor=g;b.fn.modal.noConflict=function(){b.fn.modal=i;return this};b(document).on("click.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),d=c.attr("href"),
e=b(c.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,""));d=e.data("modal")?"toggle":b.extend({remote:!/#/.test(d)&&d},e.data(),c.data());a.preventDefault();e.modal(d).one("hide",function(){c.focus()})})})(window.jQuery);
(function(b){var g=function(a,c){this.init("tooltip",a,c)};g.prototype={constructor:g,init:function(a,c,d){var e;this.type=a;this.$element=b(c);this.options=this.getOptions(d);this.enabled=true;c=this.options.trigger.split(" ");for(d=c.length;d--;){e=c[d];if(e=="click")this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else if(e!="manual"){a=e=="hover"?"mouseenter":"focus";e=e=="hover"?"mouseleave":"blur";this.$element.on(a+"."+this.type,this.options.selector,b.proxy(this.enter,
this));this.$element.on(e+"."+this.type,this.options.selector,b.proxy(this.leave,this))}}this.options.selector?(this._options=b.extend({},this.options,{trigger:"manual",selector:""})):this.fixTitle()},getOptions:function(a){a=b.extend({},b.fn[this.type].defaults,this.$element.data(),a);if(a.delay&&typeof a.delay=="number")a.delay={show:a.delay,hide:a.delay};return a},enter:function(a){var c=b(a.currentTarget)[this.type](this._options).data(this.type);if(!c.options.delay||!c.options.delay.show)return c.show();
clearTimeout(this.timeout);c.hoverState="in";this.timeout=setTimeout(function(){c.hoverState=="in"&&c.show()},c.options.delay.show)},leave:function(a){var c=b(a.currentTarget)[this.type](this._options).data(this.type);this.timeout&&clearTimeout(this.timeout);if(!c.options.delay||!c.options.delay.hide)return c.hide();c.hoverState="out";this.timeout=setTimeout(function(){c.hoverState=="out"&&c.hide()},c.options.delay.hide)},show:function(){var a,c,d,e,f;c=b.Event("show");if(this.hasContent()&&this.enabled){this.$element.trigger(c);
if(!c.isDefaultPrevented()){a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");e=typeof this.options.placement=="function"?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement;a.detach().css({top:0,left:0,display:"block"});this.options.container?a.appendTo(this.options.container):a.insertAfter(this.$element);c=this.getPosition();d=a[0].offsetWidth;a=a[0].offsetHeight;switch(e){case "bottom":f={top:c.top+c.height,left:c.left+c.width/2-d/2};break;case "top":f=
{top:c.top-a,left:c.left+c.width/2-d/2};break;case "left":f={top:c.top+c.height/2-a/2,left:c.left-d};break;case "right":f={top:c.top+c.height/2-a/2,left:c.left+c.width};break}this.applyPlacement(f,e);this.$element.trigger("shown")}}},applyPlacement:function(a,c){var d=this.tip(),e=d[0].offsetWidth,f=d[0].offsetHeight,h,j,k;d.offset(a).addClass(c).addClass("in");h=d[0].offsetWidth;j=d[0].offsetHeight;if(c=="top"&&j!=f){a.top=a.top+f-j;k=true}if(c=="bottom"||c=="top"){c=0;if(a.left<0){c=a.left*-2;a.left=
0;d.offset(a);h=d[0].offsetWidth}this.replaceArrow(c-e+h,h,"left")}else this.replaceArrow(j-f,j,"top");k&&d.offset(a)},replaceArrow:function(a,c,d){this.arrow().css(d,a?50*(1-a/c)+"%":"")},setContent:function(){var a=this.tip(),c=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](c);a.removeClass("fade in top bottom left right")},hide:function(){function a(){var e=setTimeout(function(){c.off(b.support.transition.end).detach()},500);c.one(b.support.transition.end,function(){clearTimeout(e);
c.detach()})}var c=this.tip(),d=b.Event("hide");this.$element.trigger(d);if(!d.isDefaultPrevented()){c.removeClass("in");b.support.transition&&this.$tip.hasClass("fade")?a():c.detach();this.$element.trigger("hidden");return this}},fixTitle:function(){var a=this.$element;if(a.attr("title")||typeof a.attr("data-original-title")!="string")a.attr("data-original-title",a.attr("title")||"").attr("title","")},hasContent:function(){return this.getTitle()},getPosition:function(){var a=this.$element[0];return b.extend({},
typeof a.getBoundingClientRect=="function"?a.getBoundingClientRect():{width:a.offsetWidth,height:a.offsetHeight},this.$element.offset())},getTitle:function(){var a=this.$element,c=this.options;return a.attr("data-original-title")||(typeof c.title=="function"?c.title.call(a[0]):c.title)},tip:function(){return this.$tip=this.$tip||b(this.options.template)},arrow:function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")},validate:function(){if(!this.$element[0].parentNode){this.hide();
this.options=this.$element=null}},enable:function(){this.enabled=true},disable:function(){this.enabled=false},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(a){a=a?b(a.currentTarget)[this.type](this._options).data(this.type):this;a.tip().hasClass("in")?a.hide():a.show()},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}};var i=b.fn.tooltip;b.fn.tooltip=function(a){return this.each(function(){var c=b(this),d=c.data("tooltip"),e=typeof a=="object"&&
a;d||c.data("tooltip",d=new g(this,e));typeof a=="string"&&d[a]()})};b.fn.tooltip.Constructor=g;b.fn.tooltip.defaults={animation:true,placement:"top",selector:false,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:false,container:false};b.fn.tooltip.noConflict=function(){b.fn.tooltip=i;return this}})(window.jQuery);
(function(b){var g=function(a,c){this.init("popover",a,c)};g.prototype=b.extend({},b.fn.tooltip.Constructor.prototype,{constructor:g,setContent:function(){var a=this.tip(),c=this.getTitle(),d=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](c);a.find(".popover-content")[this.options.html?"html":"text"](d);a.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var a=this.$element,c=this.options;
return(typeof c.content=="function"?c.content.call(a[0]):c.content)||a.attr("data-content")},tip:function(){if(!this.$tip)this.$tip=b(this.options.template);return this.$tip},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}});var i=b.fn.popover;b.fn.popover=function(a){return this.each(function(){var c=b(this),d=c.data("popover"),e=typeof a=="object"&&a;d||c.data("popover",d=new g(this,e));typeof a=="string"&&d[a]()})};b.fn.popover.Constructor=g;b.fn.popover.defaults=
b.extend({},b.fn.tooltip.defaults,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});b.fn.popover.noConflict=function(){b.fn.popover=i;return this}})(window.jQuery);
(function(b){function g(a,c){var d=b.proxy(this.process,this),e=b(a).is("body")?b(window):b(a),f;this.options=b.extend({},b.fn.scrollspy.defaults,c);this.$scrollElement=e.on("scroll.scroll-spy.data-api",d);this.selector=(this.options.target||(f=b(a).attr("href"))&&f.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.$body=b("body");this.refresh();this.process()}g.prototype={constructor:g,refresh:function(){var a=this;this.offsets=b([]);this.targets=b([]);this.$body.find(this.selector).map(function(){var c=
b(this);c=c.data("target")||c.attr("href");var d=/^#\w/.test(c)&&b(c);return d&&d.length&&[[d.position().top+(!b.isWindow(a.$scrollElement.get(0))&&a.$scrollElement.scrollTop()),c]]||null}).sort(function(c,d){return c[0]-d[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})},process:function(){var a=this.$scrollElement.scrollTop()+this.options.offset,c=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),d=this.offsets,e=this.targets,f=
this.activeTarget,h;if(a>=c)return f!=(h=e.last()[0])&&this.activate(h);for(h=d.length;h--;)f!=e[h]&&a>=d[h]&&(!d[h+1]||a<=d[h+1])&&this.activate(e[h])},activate:function(a){this.activeTarget=a;b(this.selector).parent(".active").removeClass("active");a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parent("li").addClass("active");if(a.parent(".dropdown-menu").length)a=a.closest("li.dropdown").addClass("active");a.trigger("activate")}};var i=b.fn.scrollspy;b.fn.scrollspy=
function(a){return this.each(function(){var c=b(this),d=c.data("scrollspy"),e=typeof a=="object"&&a;d||c.data("scrollspy",d=new g(this,e));typeof a=="string"&&d[a]()})};b.fn.scrollspy.Constructor=g;b.fn.scrollspy.defaults={offset:10};b.fn.scrollspy.noConflict=function(){b.fn.scrollspy=i;return this};b(window).on("load",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);a.scrollspy(a.data())})})})(window.jQuery);
(function(b){var g=function(a){this.element=b(a)};g.prototype={constructor:g,show:function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),d=a.attr("data-target"),e,f;if(!d)d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,"");if(!a.parent("li").hasClass("active")){e=c.find(".active:last a")[0];f=b.Event("show",{relatedTarget:e});a.trigger(f);if(!f.isDefaultPrevented()){d=b(d);this.activate(a.parent("li"),c);this.activate(d,d.parent(),function(){a.trigger({type:"shown",relatedTarget:e})})}}},
activate:function(a,c,d){function e(){f.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");h?a.addClass("in"):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");d&&d()}var f=c.find("> .active"),h=d&&b.support.transition&&f.hasClass("fade");h?f.one(b.support.transition.end,e):e();f.removeClass("in")}};var i=b.fn.tab;b.fn.tab=function(a){return this.each(function(){var c=b(this),d=c.data("tab");d||c.data("tab",
d=new g(this));typeof a=="string"&&d[a]()})};b.fn.tab.Constructor=g;b.fn.tab.noConflict=function(){b.fn.tab=i;return this};b(document).on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();b(this).tab("show")})})(window.jQuery);
(function(b){var g=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.typeahead.defaults,c);this.matcher=this.options.matcher||this.matcher;this.sorter=this.options.sorter||this.sorter;this.highlighter=this.options.highlighter||this.highlighter;this.updater=this.options.updater||this.updater;this.source=this.options.source;this.$menu=b(this.options.menu);this.shown=false;this.listen()};g.prototype={constructor:g,select:function(){this.$element.val(this.updater(this.$menu.find(".active").attr("data-value"))).change();
return this.hide()},updater:function(a){return a},show:function(){var a=b.extend({},this.$element.position(),{height:this.$element[0].offsetHeight});this.$menu.insertAfter(this.$element).css({top:a.top+a.height,left:a.left}).show();this.shown=true;return this},hide:function(){this.$menu.hide();this.shown=false;return this},lookup:function(){var a;this.query=this.$element.val();if(!this.query||this.query.length<this.options.minLength)return this.shown?this.hide():this;return(a=b.isFunction(this.source)?
this.source(this.query,b.proxy(this.process,this)):this.source)?this.process(a):this},process:function(a){var c=this;a=b.grep(a,function(d){return c.matcher(d)});a=this.sorter(a);if(!a.length)return this.shown?this.hide():this;return this.render(a.slice(0,this.options.items)).show()},matcher:function(a){return~a.toLowerCase().indexOf(this.query.toLowerCase())},sorter:function(a){for(var c=[],d=[],e=[],f;f=a.shift();)if(f.toLowerCase().indexOf(this.query.toLowerCase()))~f.indexOf(this.query)?d.push(f):
e.push(f);else c.push(f);return c.concat(d,e)},highlighter:function(a){var c=this.query.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&");return a.replace(new RegExp("("+c+")","ig"),function(d,e){return"<strong>"+e+"</strong>"})},render:function(a){var c=this;a=b(a).map(function(d,e){d=b(c.options.item).attr("data-value",e);d.find("a").html(c.highlighter(e));return d[0]});a.first().addClass("active");this.$menu.html(a);return this},next:function(){var a=this.$menu.find(".active").removeClass("active").next();
a.length||(a=b(this.$menu.find("li")[0]));a.addClass("active")},prev:function(){var a=this.$menu.find(".active").removeClass("active").prev();a.length||(a=this.$menu.find("li").last());a.addClass("active")},listen:function(){this.$element.on("focus",b.proxy(this.focus,this)).on("blur",b.proxy(this.blur,this)).on("keypress",b.proxy(this.keypress,this)).on("keyup",b.proxy(this.keyup,this));this.eventSupported("keydown")&&this.$element.on("keydown",b.proxy(this.keydown,this));this.$menu.on("click",b.proxy(this.click,
this)).on("mouseenter","li",b.proxy(this.mouseenter,this)).on("mouseleave","li",b.proxy(this.mouseleave,this))},eventSupported:function(a){var c=a in this.$element;if(!c){this.$element.setAttribute(a,"return;");c=typeof this.$element[a]==="function"}return c},move:function(a){if(this.shown){switch(a.keyCode){case 9:case 13:case 27:a.preventDefault();break;case 38:a.preventDefault();this.prev();break;case 40:a.preventDefault();this.next();break}a.stopPropagation()}},keydown:function(a){this.suppressKeyPressRepeat=
~b.inArray(a.keyCode,[40,38,9,13,27]);this.move(a)},keypress:function(a){this.suppressKeyPressRepeat||this.move(a)},keyup:function(a){switch(a.keyCode){case 40:case 38:case 16:case 17:case 18:break;case 9:case 13:if(!this.shown)return;this.select();break;case 27:if(!this.shown)return;this.hide();break;default:this.lookup()}a.stopPropagation();a.preventDefault()},focus:function(){this.focused=true},blur:function(){this.focused=false;!this.mousedover&&this.shown&&this.hide()},click:function(a){a.stopPropagation();
a.preventDefault();this.select();this.$element.focus()},mouseenter:function(a){this.mousedover=true;this.$menu.find(".active").removeClass("active");b(a.currentTarget).addClass("active")},mouseleave:function(){this.mousedover=false;!this.focused&&this.shown&&this.hide()}};var i=b.fn.typeahead;b.fn.typeahead=function(a){return this.each(function(){var c=b(this),d=c.data("typeahead"),e=typeof a=="object"&&a;d||c.data("typeahead",d=new g(this,e));typeof a=="string"&&d[a]()})};b.fn.typeahead.defaults=
{source:[],items:8,menu:'<ul class="typeahead dropdown-menu"></ul>',item:'<li><a href="#"></a></li>',minLength:1};b.fn.typeahead.Constructor=g;b.fn.typeahead.noConflict=function(){b.fn.typeahead=i;return this};b(document).on("focus.typeahead.data-api",'[data-provide="typeahead"]',function(){var a=b(this);a.data("typeahead")||a.typeahead(a.data())})})(window.jQuery);
(function(b){var g=function(a,c){this.options=b.extend({},b.fn.affix.defaults,c);this.$window=b(window).on("scroll.affix.data-api",b.proxy(this.checkPosition,this)).on("click.affix.data-api",b.proxy(function(){setTimeout(b.proxy(this.checkPosition,this),1)},this));this.$element=b(a);this.checkPosition()};g.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=b(document).height(),c=this.$window.scrollTop(),d=this.$element.offset(),e=this.options.offset,f=e.bottom,h=e.top;if(typeof e!=
"object")f=h=e;if(typeof h=="function")h=e.top();if(typeof f=="function")f=e.bottom();a=this.unpin!=null&&c+this.unpin<=d.top?false:f!=null&&d.top+this.$element.height()>=a-f?"bottom":h!=null&&c<=h?"top":false;if(this.affixed!==a){this.affixed=a;this.unpin=a=="bottom"?d.top-c:null;this.$element.removeClass("affix affix-top affix-bottom").addClass("affix"+(a?"-"+a:""))}}};var i=b.fn.affix;b.fn.affix=function(a){return this.each(function(){var c=b(this),d=c.data("affix"),e=typeof a=="object"&&a;d||
c.data("affix",d=new g(this,e));typeof a=="string"&&d[a]()})};b.fn.affix.Constructor=g;b.fn.affix.defaults={offset:0};b.fn.affix.noConflict=function(){b.fn.affix=i;return this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};c.offsetBottom&&(c.offset.bottom=c.offsetBottom);c.offsetTop&&(c.offset.top=c.offsetTop);a.affix(c)})})})(window.jQuery);
(function(b,g){var i=b();b.fn.dropdownHover=function(a){i=i.add(this.parent());return this.each(function(){var c=b(this),d=c.parent(),e={delay:b(this).data("delay"),instantlyCloseOthers:b(this).data("close-others")},f=b.extend(true,{},{delay:500,instantlyCloseOthers:true},a,e),h;d.hover(function(j){if(!d.hasClass("open")&&!c.is(j.target))return true;f.instantlyCloseOthers===true&&i.removeClass("open");g.clearTimeout(h);d.addClass("open")},function(){h=g.setTimeout(function(){d.removeClass("open")},
f.delay)});c.hover(function(){f.instantlyCloseOthers===true&&i.removeClass("open");g.clearTimeout(h);d.addClass("open")});d.find(".dropdown-submenu").each(function(){var j=b(this),k;j.hover(function(){g.clearTimeout(k);j.children(".dropdown-menu").show();j.siblings().children(".dropdown-menu").hide()},function(){var l=j.children(".dropdown-menu");k=g.setTimeout(function(){l.hide()},f.delay)})})})};b(document).ready(function(){b('[data-hover="dropdown"]').dropdownHover()})})(jQuery,this);var interval;
function slideSwitch(){var b=$("#slideshow img.active");if(b.length==0)b=$("#slideshow img:last");var g=b.next().length?b.next():$("#slideshow img:first");b.addClass("last-active");g.css({opacity:0}).addClass("active").animate({opacity:2},1E3,function(){b.removeClass("active last-active")})}$(function(){interval=setInterval("slideSwitch()",4E3);$("#slideshow img").hover(function(){clearInterval(interval)},function(){interval=setInterval("slideSwitch()",4E3)})});